# -*- coding: utf-8 -*-
"""Auto-generated figure overlay (tools/attach_slide_figures.py).
Attached by tools/build_lock.py after each chapter module is loaded:
each figure is inserted right after the best-matching block text.
"""

SLIDE_FIGURES: dict[int, list[dict]] = {
    1: [
        dict(
            type="figure",
            file="images/fig/slide01_darvish_radiobio_p002_0.jpg", width="70%",
            caption="شکل — Biological Effects of / Ionizing Radiation",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲",
            match="Biological Effects of / Ionizing Radiation",
        ),
        dict(
            type="figure",
            file="images/fig/slide01_darvish_radiobio_p002_1.jpg", width="70%",
            caption="شکل — Biological Effects of / Ionizing Radiation",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲",
            match="Biological Effects of / Ionizing Radiation",
        ),
    ],
    2: [
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p013_0.jpg", width="70%",
            caption="شکل — Thrall & Widmer, 1998 /",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۱۳",
            match="Thrall & Widmer, 1998 /",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p003_0.jpg", width="70%",
            caption="شکل — فﻬﺮﺳﺖ : / پرتونگاري در پزشكي",
            src="اسلایدهای دکتر افضلی‌پور — ص۳",
            match="فﻬﺮﺳﺖ : / پرتونگاري در پزشكي",
        ),
    ],
    3: [
        dict(
            type="figure",
            file="images/fig/slide03_darvish_mri_p035_0.jpg", width="70%",
            caption="شکل — انرژی به محیط داده ولی مقدار این انرژی کم است که باعث گرم شدن بدن ب یمار",
            src="اسلایدهای MRI — دکتر درویش — ص۳۵",
            match="انرژی به محیط داده ولی مقدار این انرژی کم است که باعث گرم شدن بدن ب یمار",
        ),
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p123_0.jpg", width="70%",
            caption="شکل — 123 / اﺳتفاده از تجﻬيزات بﺮاي كاهش تابش گيﺮي",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۲۳",
            match="123 / اﺳتفاده از تجﻬيزات بﺮاي كاهش تابش گيﺮي",
        ),
    ],
    4: [
        dict(
            type="figure",
            file="images/fig/slide04_haghparast_mphpd_p044_0.jpg", width="70%",
            caption="شکل — ایزوتوپ پایدار آن برابر بوده ولی در ارگانهای مختلف متفاوت ا",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۴۴",
            match="ایزوتوپ پایدار آن برابر بوده ولی در ارگانهای مختلف متفاوت ا",
        ),
        dict(
            type="figure",
            file="images/fig/slide04_darvish_mri_p047_0.jpg", width="70%",
            caption="شکل — 47 / تصویر",
            src="اسلایدهای MRI — دکتر درویش — ص۴۷",
            match="47 / تصویر",
        ),
    ],
    5: [
        dict(
            type="figure",
            file="images/fig/slide05_darvish_radiobio_p006_0.jpg", width="70%",
            caption="شکل — Non-stochastic (Deterministic) Effects / اثرات غیراحتمالی یا غیر تصادفی(قطعی.)",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۶",
            match="Non-stochastic (Deterministic) Effects / اثرات غیراحتمالی یا غیر تصادفی(قطعی.)",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p091_0.jpg", width="70%",
            caption="شکل — 91 /",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۱",
            match="91 /",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p094_0.jpg", width="70%",
            caption="شکل — بنابراين شدت / 100 mrad",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۴",
            match="بنابراين شدت / 100 mrad",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p094_1.jpg", width="70%",
            caption="شکل — بنابراين شدت / 100 mrad",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۴",
            match="بنابراين شدت / 100 mrad",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p115_0.jpg", width="70%",
            caption="شکل — Factors affecting staff doses / عوامل موثر در پرتوگيري كاركنان",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۱۵",
            match="Factors affecting staff doses / عوامل موثر در پرتوگيري كاركنان",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p115_1.jpg", width="70%",
            caption="شکل — Factors affecting staff doses / عوامل موثر در پرتوگيري كاركنان",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۱۵",
            match="Factors affecting staff doses / عوامل موثر در پرتوگيري كاركنان",
        ),
    ],
    6: [
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p092_0.jpg", width="70%",
            caption="شکل — فاصله / رعايت",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۲",
            match="فاصله / رعايت",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p105_0.jpg", width="70%",
            caption="شکل — برخي از كارخانﻪ ﻫا بﻪ ساخت روﭘوش ﻫايي ﻣتشكﻞ از آلياژﻫاي باري،ﻢ / تنگستن و سرب",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۰۵",
            match="برخي از كارخانﻪ ﻫا بﻪ ساخت روﭘوش ﻫايي ﻣتشكﻞ از آلياژﻫاي باري،ﻢ / تنگستن و سرب",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p106_0.jpg", width="70%",
            caption="شکل — روﭘوش ﻫاي سربي خاص دوران بارداري نيز / وجود دارد. اين روﭘوش بﻪ طور سراسري حفاﻇ",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۰۶",
            match="روﭘوش ﻫاي سربي خاص دوران بارداري نيز / وجود دارد. اين روﭘوش بﻪ طور سراسري حفاﻇ",
        ),
    ],
    7: [
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p072_0.jpg", width="70%",
            caption="شکل — Interaction of mechanical / waves with Matter",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۷۲",
            match="Interaction of mechanical / waves with Matter",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_darvish_radiobio_p079_0.jpg", width="70%",
            caption="شکل — the radiation harm that it might cause.",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۹",
            match="the radiation harm that it might cause.",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_darvish_mri_p019_0.jpg", width="70%",
            caption="شکل — Measuring Tissue Magnetization: / For an energy transfer to occur the RF Pulse m",
            src="اسلایدهای MRI — دکتر درویش — ص۱۹",
            match="Measuring Tissue Magnetization: / For an energy transfer to occur the RF Pulse m",
        ),
    ],
    8: [
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p009_0.jpg", width="70%",
            caption="شکل — Nonlinear Threshold Response / پاسخ آستانه غیر",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۹",
            match="Nonlinear Threshold Response / پاسخ آستانه غیر",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p020_0.jpg", width="70%",
            caption="شکل — Hydrolysis of Water / • So, free radical (OH, H ) and H2O2 are toxic",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲۰",
            match="Hydrolysis of Water / • So, free radical (OH, H ) and H2O2 are toxic",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p020_1.jpg", width="70%",
            caption="شکل — Hydrolysis of Water / • So, free radical (OH, H ) and H2O2 are toxic",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲۰",
            match="Hydrolysis of Water / • So, free radical (OH, H ) and H2O2 are toxic",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p036_0.jpg", width="70%",
            caption="شکل — Membrane Leakage / نشتی غشا",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۶",
            match="Membrane Leakage / نشتی غشا",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p038_0.jpg", width="70%",
            caption="شکل — Damage to Chromosomes / آسیب به کروموزوم ها",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۸",
            match="Damage to Chromosomes / آسیب به کروموزوم ها",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p039_0.jpg", width="70%",
            caption="شکل — Cell replication: a complicated duplication of DNA",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۹",
            match="Cell replication: a complicated duplication of DNA",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p040_0.jpg", width="70%",
            caption="شکل — Direct Ionization Damage to DNA / آسیب یونیزاسیون مستقیم بهDNA",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۴۰",
            match="Direct Ionization Damage to DNA / آسیب یونیزاسیون مستقیم بهDNA",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p067_0.jpg", width="70%",
            caption="شکل — دوپلیكاسیون كروموزوم اتفاق افتاده و شكست در کروموزوم تک رشته ای ایجاد مي",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۶۷",
            match="دوپلیكاسیون كروموزوم اتفاق افتاده و شكست در کروموزوم تک رشته ای ایجاد مي",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p070_0.jpg", width="70%",
            caption="شکل — از اسلایدهای رادیوبیولوژی — دکتر درویش",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۰",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p071_0.jpg", width="70%",
            caption="شکل — Lethal Chromosome Breaks: / Rings",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۱",
            match="Lethal Chromosome Breaks: / Rings",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p073_0.jpg", width="70%",
            caption="شکل — Lethal Chromosome Breaks: / Dicentric",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۳",
            match="Lethal Chromosome Breaks: / Dicentric",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p076_0.jpg", width="70%",
            caption="شکل — Nonlethal Breaks: / Translocation and",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۶",
            match="Nonlethal Breaks: / Translocation and",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p076_1.jpg", width="70%",
            caption="شکل — Nonlethal Breaks: / Translocation and",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۶",
            match="Nonlethal Breaks: / Translocation and",
        ),
    ],
    9: [
        dict(
            type="figure",
            file="images/fig/slide09_haghparast_mphpd_p064_0.jpg", width="70%",
            caption="شکل — Driving force may be sinusoidal particles oscillate back and forth / pressure",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶۴",
            match="Driving force may be sinusoidal particles oscillate back and forth / pressure",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p001_0.jpg", width="70%",
            caption="شکل — تصویربرداری تشدید مغناطیسی",
            src="اسلایدهای MRI — دکتر درویش — ص۱",
            match="تصویربرداری تشدید مغناطیسی",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p009_0.jpg", width="70%",
            caption="شکل — پروتون ها در میدان مغناطیسی / •هسته مثل یک آهنربای کوچک عمل می کند بنابراین هسته",
            src="اسلایدهای MRI — دکتر درویش — ص۹",
            match="پروتون ها در میدان مغناطیسی / •هسته مثل یک آهنربای کوچک عمل می کند بنابراین هسته",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p009_1.jpg", width="70%",
            caption="شکل — پروتون ها در میدان مغناطیسی / •هسته مثل یک آهنربای کوچک عمل می کند بنابراین هسته",
            src="اسلایدهای MRI — دکتر درویش — ص۹",
            match="پروتون ها در میدان مغناطیسی / •هسته مثل یک آهنربای کوچک عمل می کند بنابراین هسته",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p016_0.jpg", width="70%",
            caption="شکل — تشدید بوسیله امواج رادیویی / •امواج رادیویی که فرستاده می شود باعث تشدید می شود",
            src="اسلایدهای MRI — دکتر درویش — ص۱۶",
            match="تشدید بوسیله امواج رادیویی / •امواج رادیویی که فرستاده می شود باعث تشدید می شود",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p016_1.jpg", width="70%",
            caption="شکل — تشدید بوسیله امواج رادیویی / •امواج رادیویی که فرستاده می شود باعث تشدید می شود",
            src="اسلایدهای MRI — دکتر درویش — ص۱۶",
            match="تشدید بوسیله امواج رادیویی / •امواج رادیویی که فرستاده می شود باعث تشدید می شود",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p017_0.jpg", width="70%",
            caption="شکل — Measuring Tissue Magnetization: / When Mo is aligned to the magnetic field Bo it",
            src="اسلایدهای MRI — دکتر درویش — ص۱۷",
            match="Measuring Tissue Magnetization: / When Mo is aligned to the magnetic field Bo it",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p046_0.jpg", width="70%",
            caption="شکل — 46 / تصویر",
            src="اسلایدهای MRI — دکتر درویش — ص۴۶",
            match="46 / تصویر",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p048_0.jpg", width="70%",
            caption="شکل — تصویرPROTON / DENSITY",
            src="اسلایدهای MRI — دکتر درویش — ص۴۸",
            match="تصویرPROTON / DENSITY",
        ),
    ],
}
