# -*- coding: utf-8 -*-
"""Auto-generated figure overlay (tools/attach_slide_figures.py).
Attached by tools/build_lock.py after each chapter module is loaded:
each figure is inserted right after the best-matching block text.
"""

SLIDE_FIGURES: dict[int, list[dict]] = {
    1: [
        dict(
            type="figure",
            file="images/fig/slide01_darvish_radiobio_p002_0.jpg", width="70%",
            caption="شکل — اثرات بیولوژیکی پرتوهای یونیزان",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲",
            match="Biological Effects of Ionizing Radiation اثرات بیولوژیکی پرتوهای یونیزان ",
        ),
        dict(
            type="figure",
            file="images/fig/slide01_afzalipour_p065_0.jpg", width="70%",
            caption="شکل — از اسلایدهای دکتر افضلی‌پور",
            src="اسلایدهای دکتر افضلی‌پور — ص۶۵",
            match="",
        ),
    ],
    2: [
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p005_0.jpg", width="70%",
            caption="شکل — Electromagnetic Spectrum",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۵",
            match="Electromagnetic Spectrum ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p006_0.jpg", width="70%",
            caption="شکل — Electromagnetic spectrum",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶",
            match="Electromagnetic spectrum ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p009_0.jpg", width="70%",
            caption="شکل — X-ray Production",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۹",
            match="X-ray Production Bremsstrahlung Characteristic ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p013_0.jpg", width="70%",
            caption="شکل — Thrall & Widmer, 1998",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۱۳",
            match="Thrall & Widmer, 1998 ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p014_0.jpg", width="70%",
            caption="شکل — Thrall & Widmer, 1998",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۱۴",
            match="Thrall & Widmer, 1998 ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_darvish_radiobio_p023_0.jpg", width="70%",
            caption="شکل — تصویری از برهمکنش مستقیم و غیر مستقی",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲۳",
            match="تصویری از برهمکنش مستقیم و غیر مستقی م ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p003_0.jpg", width="70%",
            caption="شکل — فﻬﺮﺳﺖ : / پرتونگاري در پزشكي",
            src="اسلایدهای دکتر افضلی‌پور — ص۳",
            match="فﻬﺮﺳﺖ : / پرتونگاري در پزشكي",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p019_0.jpg", width="70%",
            caption="شکل — X-ray Radiography / •",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۹",
            match="X-ray Radiography / •",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p019_1.jpg", width="70%",
            caption="شکل — X-ray Radiography / •",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۹",
            match="X-ray Radiography / •",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p020_0.jpg", width="70%",
            caption="شکل — Electromagnetic Radiation / Spectrum",
            src="اسلایدهای دکتر افضلی‌پور — ص۲۰",
            match="Electromagnetic Radiation / Spectrum",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p077_0.jpg", width="70%",
            caption="شکل — تابش گيﺮي بيمار / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۷۷",
            match="تابش گيﺮي بيمار / ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p087_0.jpg", width="70%",
            caption="شکل — بيمار باردار / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۸۷",
            match="بيمار باردار / ",
        ),
    ],
    3: [
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p053_0.jpg", width="70%",
            caption="شکل — • / 53",
            src="اسلایدهای دکتر افضلی‌پور — ص۵۳",
            match="• / 53",
        ),
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p061_0.jpg", width="70%",
            caption="شکل — اصول عملكﺮد : پرتوهاي ايكس از قﺴﻤﺖ باﻻيي دستگاه سي آرم به سﻤﺖ ناحيه هدف تاب / ان",
            src="اسلایدهای دکتر افضلی‌پور — ص۶۱",
            match="اصول عملكﺮد : پرتوهاي ايكس از قﺴﻤﺖ باﻻيي دستگاه سي آرم به سﻤﺖ ناحيه هدف تاب / ان",
        ),
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p123_0.jpg", width="70%",
            caption="شکل — 123 / اﺳتفاده از تجﻬيزات بﺮاي كاهش تابش گيﺮي",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۲۳",
            match="123 / اﺳتفاده از تجﻬيزات بﺮاي كاهش تابش گيﺮي",
        ),
    ],
    4: [
        dict(
            type="figure",
            file="images/fig/slide04_haghparast_mphpd_p044_0.jpg", width="70%",
            caption="شکل — ایزوتوپ پایدار آن برابر بوده ولی در ارگانهای مختلف متفاوت ا",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۴۴",
            match="نیمه عمرموثر: از رابطه زیر محاسبه میشود:  نیمه عمر فیزیکیt½رادیوایزوتوپهای هر عنصر متفاوت است – مثالٌ نیمه عمرI 125 ، 60 روز وI 131 ، 8روز است  نیمه عمر بیولژیکیt½b برای کلیه رادیوایزوتوپهای هر عنصر و ایزوتوپ پایدار آن برابر بوده ولی در ارگانهای مختلف متفاوت ا ست – مثالٌ نیمه عمر بیولژیکیI 125 ، I 131 و ایزوتوپ پایدارI 127در تیروئید140 روز و در کلیه و کبد7 روز است 2 1 2 1 2 1 t 1 t 1 t 1 b eff + = ",
        ),
        dict(
            type="figure",
            file="images/fig/slide04_darvish_mri_p047_0.jpg", width="70%",
            caption="شکل — تصویر",
            src="اسلایدهای MRI — دکتر درویش — ص۴۷",
            match="47 تصویر مغز با وزنT2 ",
        ),
    ],
    5: [
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p059_0.jpg", width="70%",
            caption="شکل — فلورﺳكوپيFluoroscopy / تفاوت راديوگرافي و فﻠوروسكوپي: ) راديولوژي ﺛﺒت لﺤﻈه اي و",
            src="اسلایدهای دکتر افضلی‌پور — ص۵۹",
            match="فلورﺳكوپيFluoroscopy / تفاوت راديوگرافي و فﻠوروسكوپي: ) راديولوژي ﺛﺒت لﺤﻈه اي و",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p091_0.jpg", width="70%",
            caption="شکل — 91 /",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۱",
            match="91 /",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p094_0.jpg", width="70%",
            caption="شکل — بنابراين شدت / 100 mrad",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۴",
            match="بنابراين شدت / 100 mrad",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p094_1.jpg", width="70%",
            caption="شکل — بنابراين شدت / 100 mrad",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۴",
            match="بنابراين شدت / 100 mrad",
        ),
    ],
    6: [
        dict(
            type="figure",
            file="images/fig/slide06_darvish_radiobio_p037_0.jpg", width="70%",
            caption="شکل — اتصال مجدد آن، ممکن است باعث تکثیر سلول در حالت",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۷",
            match="DNA - the Target of Radiation Protection DNA -هدف حفاظت در برابر تشعشع • The double-helical structure of DNA carries the genetic code for the cell. Breakage of the strand by radiation plus an error in its rejoining, may cause the cell to proliferate in an erroneous mode (cancer) or to die. • ساختار دوگانه مارپیچیDNA حامل کد ژنتیکی سلول است .شکستن رشته توسط تشعشع به عالوه یک خ طا در اتصال مجدد آن، ممکن است باعث تکثیر سلول در حالت اشتباه(سرطان )یا مرگ شود. ",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_darvish_radiobio_p081_0.jpg", width="70%",
            caption="شکل — در حفاظت در برابر تشعشع باید موارد زیر را در نظر گرفت:",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۸۱",
            match="In radiation protection should be consider: در حفاظت در برابر تشعشع باید موارد زیر را در نظر گرفت: 1 .کاهش زمان در معرض قرارگیری پرتو 2 .افزایش فاصله از منبع پرتوزا 3 .استفاده از حفاظ پرتوی مانند : سرب، بتون، آلومینیوم و... ",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p081_0.jpg", width="70%",
            caption="شکل — روپوش هاي محافظ، دﺳتكش و حفاظ گونادها / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۸۱",
            match="روپوش هاي محافظ، دﺳتكش و حفاظ گونادها / ",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p090_0.jpg", width="70%",
            caption="شکل — زمان / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۰",
            match="زمان / ",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p092_0.jpg", width="70%",
            caption="شکل — فاصله / رعايت",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۲",
            match="فاصله / رعايت",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p104_0.jpg", width="70%",
            caption="شکل —  / يك روﭘﻮش سﺮﺑي ﺣﺪود",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۰۴",
            match=" / يك روﭘﻮش سﺮﺑي ﺣﺪود",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p105_0.jpg", width="70%",
            caption="شکل — برخي از كارخانﻪ ﻫا بﻪ ساخت روﭘوش ﻫايي ﻣتشكﻞ از آلياژﻫاي باري،ﻢ / تنگستن و سرب",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۰۵",
            match="برخي از كارخانﻪ ﻫا بﻪ ساخت روﭘوش ﻫايي ﻣتشكﻞ از آلياژﻫاي باري،ﻢ / تنگستن و سرب ",
        ),
    ],
    7: [
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p063_0.jpg", width="70%",
            caption="شکل — از اسلایدهای M.Ph.P.D — دکتر حق‌پرست",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶۳",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p091_0.jpg", width="70%",
            caption="شکل — از اسلایدهای M.Ph.P.D — دکتر حق‌پرست",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۹۱",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p091_1.jpg", width="70%",
            caption="شکل — از اسلایدهای M.Ph.P.D — دکتر حق‌پرست",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۹۱",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_darvish_radiobio_p079_0.jpg", width="70%",
            caption="شکل — the radiation harm that it might cause.",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۹",
            match="Justification توجیه پذیری اقدام • Justification means that any exposure produces sufficient benefit to offset the radiation harm that it might cause. • Thus, if the exposure has not any benefit it is not justified. •توجیه پذیری به این معناست که هرگونه قرار گر فتن در معرض پرتو فواید و سود کافی برای جبران آس یب پرتوی که ممکن است ایجاد،کند داشته باشد. •بنابراین،اگر قرار گرفتن در معرض پرتو هیچ من فعتی نداشته،باشد موجه نیست. ",
        ),
    ],
    8: [
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p005_0.jpg", width="70%",
            caption="شکل — •هم در سلول های در معرض مستقیم پرتو و هم در سلول های مواجه نشده",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۵",
            match="Stochastic (Random) Effects اثرات احتمالی(تصادفی) • Occur by chance • Occur in both exposed and unexposed individuals • Probability of occurrence increases as dose increases •به صورت اتفاقی رخ می دهد •هم در سلول های در معرض مستقیم پرتو و هم در سلول های مواجه نشده با پرتو مستقیم رخ می دهد. • احتمال وقوع با افزایش دوز افزایش می یابد. ",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p034_0.jpg", width="70%",
            caption="شکل — انحراف یا ناهنجاری کروموزومی",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۴",
            match="Ring Chromosome Aberration انحراف یا ناهنجاری کروموزومی حلقه ",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p036_0.jpg", width="70%",
            caption="شکل — Membrane Leakage",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۶",
            match="Membrane Leakage نشتی غشا ",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p038_0.jpg", width="70%",
            caption="شکل — کروموزوم های آسیب دیده در میکروسکوپ نوری",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۸",
            match="Damage to Chromosomes آسیب به کروموزوم ها • The damaged chromosomes are visible in light microscopy • Ring Formation and Dicentrics are characteristic indicators of damage • کروموزوم های آسیب دیده در میکروسکوپ نوری قابل مشاهده هستند. • تشکیل حلقه و دی سانتریک شاخص های مشخص ه آسیب هستند. ",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p040_0.jpg", width="70%",
            caption="شکل — ًپرتوهای یونیزه ممکن است مستقیما",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۴۰",
            match="Direct Ionization Damage to DNA آسیب یونیزاسیون مستقیم بهDNA • Ionizing Radiation may directly break bonds in the DNA molecule. • Damage remains when the DNA cannot repair the bond breaks • ًپرتوهای یونیزه ممکن است مستقیما پیوندهای موجود در مولکولDNA را بشکند . هنگامی کهDNA نتواند شکستگی پیوند را ترمیم کند، آسی ب باقی می ماند. ",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p052_0.jpg", width="70%",
            caption="شکل — DNA is the critical target for radiation damage",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۵۲",
            match="DNA DNA is the critical target for radiation damage sugar- phosphate backbone base minor groove 1.2 nm major groove 1.8 nm 2 nm ",
        ),
    ],
    9: [
        dict(
            type="figure",
            file="images/fig/slide09_haghparast_mphpd_p064_0.jpg", width="70%",
            caption="شکل — Driving force may be sinusoidal particles oscillate back and forth",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶۴",
            match="Driving force may be sinusoidal particles oscillate back and forth pressure time Period ",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p002_0.jpg", width="70%",
            caption="شکل — از اسلایدهای MRI — دکتر درویش",
            src="اسلایدهای MRI — دکتر درویش — ص۲",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p048_0.jpg", width="70%",
            caption="شکل — تصویرPROTON",
            src="اسلایدهای MRI — دکتر درویش — ص۴۸",
            match=" تصویرPROTON DENSITY ",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p051_0.jpg", width="70%",
            caption="شکل — کنتراست خونریزی درMRI",
            src="اسلایدهای MRI — دکتر درویش — ص۵۱",
            match=" کنتراست خونریزی درMRI ",
        ),
    ],
}
