# -*- coding: utf-8 -*-
"""Auto-generated figure overlay (tools/attach_slide_figures.py).
Attached by tools/build_lock.py after each chapter module is loaded:
each figure is inserted right after the best-matching block text.
"""

SLIDE_FIGURES: dict[int, list[dict]] = {
    1: [
        dict(
            type="figure",
            file="images/fig/slide01_darvish_radiobio_p002_0.jpg", width="70%",
            caption="شکل — اثرات بیولوژیکی پرتوهای یونیزان",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲",
            match="اثرات بیولوژیکی پرتوهای یونیزان",
        ),
        dict(
            type="figure",
            file="images/fig/slide01_afzalipour_p065_0.jpg", width="70%",
            caption="شکل — از اسلایدهای دکتر افضلی‌پور",
            src="اسلایدهای دکتر افضلی‌پور — ص۶۵",
            match="",
        ),
    ],
    2: [
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p005_0.jpg", width="70%",
            caption="شکل — Electromagnetic Spectrum",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۵",
            match="Electromagnetic Spectrum",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p006_0.jpg", width="70%",
            caption="شکل — Electromagnetic spectrum",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶",
            match="Electromagnetic spectrum",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p009_0.jpg", width="70%",
            caption="شکل — X-ray Production",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۹",
            match="X-ray Production",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p013_0.jpg", width="70%",
            caption="شکل — Thrall & Widmer, 1998",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۱۳",
            match="Thrall & Widmer, 1998",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_haghparast_mphpd_p014_0.jpg", width="70%",
            caption="شکل — Thrall & Widmer, 1998",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۱۴",
            match="Thrall & Widmer, 1998",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_darvish_radiobio_p023_0.jpg", width="70%",
            caption="شکل — تصویری از برهمکنش مستقیم و غیر مستقی",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۲۳",
            match="تصویری از برهمکنش مستقیم و غیر مستقی",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p003_0.jpg", width="70%",
            caption="شکل — فﻬﺮﺳﺖ : / پرتونگاري در پزشكي",
            src="اسلایدهای دکتر افضلی‌پور — ص۳",
            match="فﻬﺮﺳﺖ : / پرتونگاري در پزشكي",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p019_0.jpg", width="70%",
            caption="شکل — X-ray Radiography / •",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۹",
            match="X-ray Radiography / •",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p019_1.jpg", width="70%",
            caption="شکل — X-ray Radiography / •",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۹",
            match="X-ray Radiography / •",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p020_0.jpg", width="70%",
            caption="شکل — Electromagnetic Radiation / Spectrum",
            src="اسلایدهای دکتر افضلی‌پور — ص۲۰",
            match="Electromagnetic Radiation / Spectrum",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p077_0.jpg", width="70%",
            caption="شکل — تابش گيﺮي بيمار / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۷۷",
            match="تابش گيﺮي بيمار / ",
        ),
        dict(
            type="figure",
            file="images/fig/slide02_afzalipour_p087_0.jpg", width="70%",
            caption="شکل — بيمار باردار / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۸۷",
            match="بيمار باردار / ",
        ),
    ],
    3: [
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p053_0.jpg", width="70%",
            caption="شکل — • / 53",
            src="اسلایدهای دکتر افضلی‌پور — ص۵۳",
            match="• / 53",
        ),
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p061_0.jpg", width="70%",
            caption="شکل — اصول عملكﺮد : پرتوهاي ايكس از قﺴﻤﺖ باﻻيي دستگاه سي آرم به سﻤﺖ ناحيه هدف تاب / ان",
            src="اسلایدهای دکتر افضلی‌پور — ص۶۱",
            match="اصول عملكﺮد : پرتوهاي ايكس از قﺴﻤﺖ باﻻيي دستگاه سي آرم به سﻤﺖ ناحيه هدف تاب / ان",
        ),
        dict(
            type="figure",
            file="images/fig/slide03_afzalipour_p123_0.jpg", width="70%",
            caption="شکل — 123 / اﺳتفاده از تجﻬيزات بﺮاي كاهش تابش گيﺮي",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۲۳",
            match="123 / اﺳتفاده از تجﻬيزات بﺮاي كاهش تابش گيﺮي",
        ),
    ],
    4: [
        dict(
            type="figure",
            file="images/fig/slide04_haghparast_mphpd_p044_0.jpg", width="70%",
            caption="شکل — ایزوتوپ پایدار آن برابر بوده ولی در ارگانهای مختلف متفاوت ا",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۴۴",
            match="ایزوتوپ پایدار آن برابر بوده ولی در ارگانهای مختلف متفاوت ا",
        ),
        dict(
            type="figure",
            file="images/fig/slide04_darvish_mri_p047_0.jpg", width="70%",
            caption="شکل — تصویر",
            src="اسلایدهای MRI — دکتر درویش — ص۴۷",
            match="تصویر",
        ),
    ],
    5: [
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p059_0.jpg", width="70%",
            caption="شکل — فلورﺳكوپيFluoroscopy / تفاوت راديوگرافي و فﻠوروسكوپي: ) راديولوژي ﺛﺒت لﺤﻈه اي و",
            src="اسلایدهای دکتر افضلی‌پور — ص۵۹",
            match="فلورﺳكوپيFluoroscopy / تفاوت راديوگرافي و فﻠوروسكوپي: ) راديولوژي ﺛﺒت لﺤﻈه اي و",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p091_0.jpg", width="70%",
            caption="شکل — 91 /",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۱",
            match="91 /",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p094_0.jpg", width="70%",
            caption="شکل — بنابراين شدت / 100 mrad",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۴",
            match="بنابراين شدت / 100 mrad",
        ),
        dict(
            type="figure",
            file="images/fig/slide05_afzalipour_p094_1.jpg", width="70%",
            caption="شکل — بنابراين شدت / 100 mrad",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۴",
            match="بنابراين شدت / 100 mrad",
        ),
    ],
    6: [
        dict(
            type="figure",
            file="images/fig/slide06_darvish_radiobio_p037_0.jpg", width="70%",
            caption="شکل — اتصال مجدد آن، ممکن است باعث تکثیر سلول در حالت",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۷",
            match="اتصال مجدد آن، ممکن است باعث تکثیر سلول در حالت",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_darvish_radiobio_p081_0.jpg", width="70%",
            caption="شکل — در حفاظت در برابر تشعشع باید موارد زیر را در نظر گرفت:",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۸۱",
            match="در حفاظت در برابر تشعشع باید موارد زیر را در نظر گرفت:",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p081_0.jpg", width="70%",
            caption="شکل — روپوش هاي محافظ، دﺳتكش و حفاظ گونادها / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۸۱",
            match="روپوش هاي محافظ، دﺳتكش و حفاظ گونادها / ",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p090_0.jpg", width="70%",
            caption="شکل — زمان / ",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۰",
            match="زمان / ",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p092_0.jpg", width="70%",
            caption="شکل — فاصله / رعايت",
            src="اسلایدهای دکتر افضلی‌پور — ص۹۲",
            match="فاصله / رعايت",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p104_0.jpg", width="70%",
            caption="شکل —  / يك روﭘﻮش سﺮﺑي ﺣﺪود",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۰۴",
            match=" / يك روﭘﻮش سﺮﺑي ﺣﺪود",
        ),
        dict(
            type="figure",
            file="images/fig/slide06_afzalipour_p105_0.jpg", width="70%",
            caption="شکل — برخي از كارخانﻪ ﻫا بﻪ ساخت روﭘوش ﻫايي ﻣتشكﻞ از آلياژﻫاي باري،ﻢ / تنگستن و سرب",
            src="اسلایدهای دکتر افضلی‌پور — ص۱۰۵",
            match="برخي از كارخانﻪ ﻫا بﻪ ساخت روﭘوش ﻫايي ﻣتشكﻞ از آلياژﻫاي باري،ﻢ / تنگستن و سرب",
        ),
    ],
    7: [
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p063_0.jpg", width="70%",
            caption="شکل — از اسلایدهای M.Ph.P.D — دکتر حق‌پرست",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶۳",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p091_0.jpg", width="70%",
            caption="شکل — از اسلایدهای M.Ph.P.D — دکتر حق‌پرست",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۹۱",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_haghparast_mphpd_p091_1.jpg", width="70%",
            caption="شکل — از اسلایدهای M.Ph.P.D — دکتر حق‌پرست",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۹۱",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide07_darvish_radiobio_p079_0.jpg", width="70%",
            caption="شکل — the radiation harm that it might cause.",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۷۹",
            match="the radiation harm that it might cause.",
        ),
    ],
    8: [
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p005_0.jpg", width="70%",
            caption="شکل — •هم در سلول های در معرض مستقیم پرتو و هم در سلول های مواجه نشده",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۵",
            match="•هم در سلول های در معرض مستقیم پرتو و هم در سلول های مواجه نشده",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p034_0.jpg", width="70%",
            caption="شکل — انحراف یا ناهنجاری کروموزومی",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۴",
            match="انحراف یا ناهنجاری کروموزومی",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p036_0.jpg", width="70%",
            caption="شکل — Membrane Leakage",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۶",
            match="Membrane Leakage",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p038_0.jpg", width="70%",
            caption="شکل — کروموزوم های آسیب دیده در میکروسکوپ نوری",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۳۸",
            match="کروموزوم های آسیب دیده در میکروسکوپ نوری",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p040_0.jpg", width="70%",
            caption="شکل — ًپرتوهای یونیزه ممکن است مستقیما",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۴۰",
            match="ًپرتوهای یونیزه ممکن است مستقیما",
        ),
        dict(
            type="figure",
            file="images/fig/slide08_darvish_radiobio_p052_0.jpg", width="70%",
            caption="شکل — DNA is the critical target for radiation damage",
            src="اسلایدهای رادیوبیولوژی — دکتر درویش — ص۵۲",
            match="DNA is the critical target for radiation damage",
        ),
    ],
    9: [
        dict(
            type="figure",
            file="images/fig/slide09_haghparast_mphpd_p064_0.jpg", width="70%",
            caption="شکل — Driving force may be sinusoidal particles oscillate back and forth",
            src="اسلایدهای M.Ph.P.D — دکتر حق‌پرست — ص۶۴",
            match="Driving force may be sinusoidal particles oscillate back and forth",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p002_0.jpg", width="70%",
            caption="شکل — از اسلایدهای MRI — دکتر درویش",
            src="اسلایدهای MRI — دکتر درویش — ص۲",
            match="",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p048_0.jpg", width="70%",
            caption="شکل — تصویرPROTON",
            src="اسلایدهای MRI — دکتر درویش — ص۴۸",
            match="تصویرPROTON",
        ),
        dict(
            type="figure",
            file="images/fig/slide09_darvish_mri_p051_0.jpg", width="70%",
            caption="شکل — کنتراست خونریزی درMRI",
            src="اسلایدهای MRI — دکتر درویش — ص۵۱",
            match="کنتراست خونریزی درMRI",
        ),
    ],
}
